# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.


#title: Your awesome title
  #email: fake@email.com

title: zolutal's blog
author:
  name: ""
  email: ""

description: >-

theme: minima

plugins:
  - jekyll-seo-tag
#  - jekyll-feed

minima:
  skin: dark
  date_format: "%b %-d, %Y"
  social_links:
    - { platform: github,  user_url: "https://github.com/zolutal" }
    - { platform: twitter,  user_url: "https://twitter.com/zolutal" }
    - { platform: mastodon, user_url: "https://infosec.exchange/@zolutal"}
